TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += ldens3300.db
DATA += ldens3300.proto

#=======================================
include $(TOP)/configure/RULES
